### ISSUE TITLE
A candidate of FOF finder

### ISSUE THREAD

**Issue by syrte** [Kambrian/HBT2#2]
It seems the open source code [kdcount](https://github.com/rainwoodman/kdcount) is a good choice or at least a good reference.
It uses KDTree and is optimized for zooming simulation though works well also for usual cosmological simulations. And it has a python wrapper for interface.
The best point as I see, it's well modularized.
It is written by [Yu Feng](http://rainwoodman.github.io/website/) from Berkeley Center for Cosmological Physics. 

It is not parallelized yet itself, though it has a parallelized application in [nbodykit](https://github.com/bccp/nbodykit/).

As I tested, it can identificate fofs for a zooming simulation with 3e8 particles in 30 minutes.
For 1e9 particles cosmological simulation, it takes about 1 h.
I've no idea how good is the performance, seems not bad. At least it's much faster than fixed grids methods (i.e.  Huiyuan's variant of Jing's fof code).

Its output seems to be reasonable, though slightly different from the previous output from Jing's fof finder when same linking length used.
I'll make some more check on its outputs.

However, I've no time to go deep into the code. 
I just use its python wrap for the moment.
Still many works to do if we want to integrate it into HBT.

**Comment by Kambrian** [comment]
Thanks for this information!  

It looks pretty neat and it seems to be parallelized internally as well. To cooperate with HBT, the easiest way is to write a read function for its output, after running the FoF independently. And yes it's even better to integrate it into the main program at a lower level, to save some IO time and simplify the workflow.   

For the performance, actually HBT-1 provides a serial oct-tree FoF finder (though using gravity tree rather than geometric tree so the performance is not optimal). Do you have an idea how they compare?

If not for floating point error, the FoF algorithms are expected to produce identical results. So it's worth checking the outputs further.

**Comment by syrte** [comment]
Sorry for late response. I didn't make any detailed comparision yet.
Glad to know now you have FoF implementation in HBT2.
So, I'll close this.

**Comment by Kambrian** [comment]
The new implementation in HBT2 is actually faster and scales better.

**Comment by syrte** [comment]
Great job!
